Databases week1
andrii1/hyf-homework pull request #13
Opened 2022-08-26 10:10 UTC by andrii1

2022-08-30 11:34 UTC, 27ManishaPatel commented on databases/week1/index.sql
> +Get the title and due date of all tasks where the title or description contains database
Question you can write as a comment 😊

2022-08-30 11:34 UTC, 27ManishaPatel commented on databases/week1/index.sql
> +/*Get all the tasks, sorted with the most recently created first*/
You can use  ' --Get all the tasks, sorted with the most recently created first ' for single line comments

2022-08-30 11:34 UTC, 27ManishaPatel commented on databases/week1/index.sql
> +SELECT status.name, COUNT(*) as number FROM task JOIN status ON status.id = task.status_id GROUP BY status.name ORDER BY number DESC
good work!

2022-09-05 10:13 UTC, Elia-Git requested changes
Pls implement given feedback from Manisha.

2022-10-06 13:57 UTC, merged