Databases week3
andrii1/hyf-homework pull request #15
Opened 2022-09-02 19:44 UTC by andrii1

2022-09-04 22:10 UTC, Elia-Git requested changes
Few comments for a qiuck fix

2022-09-04 22:10 UTC, Elia-Git commented on databases/week3/queries.sql
> +) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
good

2022-09-04 22:10 UTC, Elia-Git commented on databases/week3/additional_queries.sql
> +  100;
Remove lines 9 & 10 , why we should limit to 100 meals...? we should test all meals if they fulfill above condition

2022-09-04 22:10 UTC, Elia-Git commented on databases/week3/additional_queries.sql
> +  100;
Remove , no need to find for  a limited nr. of meals

2022-09-28 10:50 UTC, 27ManishaPatel approved these changes
well done!

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/queries.sql
> +) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci;
Good Database !

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/queries.sql
> +            or multiple attributes*/
I prefer to write comment in 1 or 2 line instead of 6 lines 😊

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/queries.sql
> -      fx 1*/
This comment should not be here Right ?

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/additional_queries.sql
> +LIMIT
I think No need to use LIMIT here

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/additional_queries.sql
> +  /*Get only specific number of meals fx return only 5 meals*/
good 👍

2022-09-28 10:50 UTC, 27ManishaPatel commented on databases/week3/additional_queries.sql
> +  AVG(review.stars) ASC
great!

2022-10-06 13:58 UTC, merged