Nodejs week1
andrii1/hyf-homework pull request #16
Opened 2022-09-17 15:30 UTC by andrii1

2022-09-21 09:09 UTC, dpfernandes requested changes
@andrii1 you are changing 2.384 files and nobody is going to review it :) 

Please fix this PR(or create a new one) so that you commit only the files that you worked on for the NodeJS-Week1

2022-09-21 12:11 UTC, andrii1 commented
> @andrii1 you are changing 2.384 files and nobody is going to review it :)
> 
> Please fix this PR(or create a new one) so that you commit only the files that you worked on for the NodeJS-Week1

ok done!

2022-09-23 12:49 UTC, Divyajg approved these changes
Logic flow is impressive.
Great work. 👍

2022-09-28 11:01 UTC, 27ManishaPatel approved these changes
Good work !

2022-09-28 11:01 UTC, 27ManishaPatel commented on nodejs/week1/nodejs-week1/app.js
> +});
for gmail user isn’t it LIKE '%@gmail %'?

2022-09-28 11:01 UTC, 27ManishaPatel commented on nodejs/week1/nodejs-week1/app.js
> +
Good job !

2022-09-28 11:01 UTC, 27ManishaPatel commented on nodejs/week1/avg.js
> +}
Great !

2022-10-06 15:40 UTC, merged