homework
andrii1/hyf-homework pull request #21
Opened 2022-10-08 19:39 UTC by andrii1

2022-10-10 08:34 UTC, dpfernandes commented
Can you please write a descriptive title for this PR as it's requested on the homework?

2022-10-10 18:25 UTC, andrii1 commented
> Can you please write a descriptive title for this PR as it's requested on the homework?

changed!

2022-10-11 11:02 UTC, annamourasobral requested changes
Hey, @andrii1 
Since it's the same app some of my requests are also in PR #22.
Don't forget to style it.
Happy coding! 👩🏻‍💻

2022-10-11 11:02 UTC, annamourasobral commented on react/react1/week1/todolist/src/App.js
> +      <Table />
there's no table, so I would recommend you change the name to todo list instead

2022-10-11 11:02 UTC, annamourasobral commented on react/react1/week1/todolist/src/components/ItemDeadline.js
> +function ItemDeadline({ deadline }) {
over nesting

2022-10-11 11:02 UTC, annamourasobral commented on react/react1/week1/todolist/src/components/ItemDescription.js
> +function ItemDescription({ description }) {
over nesting

2022-10-11 11:02 UTC, annamourasobral commented on react/react1/week1/todolist/src/components/Table.js
> +const items = [
separate in another file

2022-10-11 11:02 UTC, annamourasobral commented on react/react1/week1/todolist/src/components/Table.js
> +        <ItemRow description={description} deadline={deadline} key={id} />
these props should only be accessed inside the item

2023-06-03 12:09 UTC, merged